name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: "12.x" 
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          channel: 'stable'
      - run: flutter build apk
          

      - name: Get dependencies
        run: flutter pub get
      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle
