name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
       
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
       
      - uses: subosito/flutter-action@v2
        with:
          
          flutter-version: "3.7.7"
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
        # Upload generated apk to the artifacts.
        
      - uses: actions/upload-artifact@v3
        with:
         name: Relatório
         path: build/app/outputs/apk/release/app-release.apk
