name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: "12.x"
          
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          channel: 'stable'
          
      
      - name: Get dependencies
        run: flutter pub get
        
        # Check for any formatting issues in the code.
      #- run: flutter format --set-exit-if-changed .
      
      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
      
      # Run widget tests for our flutter project.
      - run: flutter test
      
       # Build apk.
      - run: flutter build apk
      
      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
         name: release-apk
         path: build/app/outputs/apk/release/app-release.apk
